entries:
  en:
    f:
      - title: Back to documentation
        url: /documentation/index.html

  ru:
    f:
      - title: Назад к документации
        type: secondary
        url: /documentation/index.html

      - title: К выбору языка и CI-системы
        type: secondary
        url: /documentation/guides/applications_guide/



